### ISSUE TITLE
配置了cookie的，签到失败

### ISSUE THREAD

**Issue by deYangar** [wickedll/genshin_sign#1]
### **系统版本**
Windows 10 专业版 21H1

### **Node.js 版本**
v13.13.0

### **应用版本**
v2.2.2

### **启动方式**
Forever

### **复述操作**
这个qq号已经绑定了cookie，然后本地cookies.yml也设置了，但是签到的话显示没登录，然后控制台里有反应。
![20211207232417](https://user-images.githubusercontent.com/70438628/145066945-4880a95f-ea7e-4a82-8205-7f6a7857fb58.jpg)
![QQ截图20211208000639](https://user-images.githubusercontent.com/70438628/145066969-a1e8c3de-7153-43a2-a0be-83deca46b6fe.jpg)

### **配置文件**
genshin_sign.yml修改

openTiming: true #是否开启定时功能
cron: "0 0 0 * * *" #自动签到时间
serverPort: 58613 #对外开放api端口号

commands.yml修改

genshin.mys.sign:
  type: order
  auth: 1
  scope: 3
  headers:
    - mysqd
    - mys签到
    - 米游社签到
  enable: true

### **错误报告**
无错误报告

**Comment by deYangar** [comment]
> ### **系统版本**
> Windows 10 专业版 21H1
> 
> ### **Node.js 版本**
> v13.13.0
> 
> ### **应用版本**
> v2.2.2
> 
> ### **启动方式**
> Forever
> 
> ### **复述操作**
> 这个qq号已经绑定了cookie，然后本地cookies.yml也设置了，但是签到的话显示没登录，然后控制台里有反应。 ![20211207232417](https://user-images.githubusercontent.com/70438628/145066945-4880a95f-ea7e-4a82-8205-7f6a7857fb58.jpg) ![QQ截图20211208000639](https://user-images.githubusercontent.com/70438628/145066969-a1e8c3de-7153-43a2-a0be-83deca46b6fe.jpg)
> 
> ### **配置文件**
> genshin_sign.yml修改
> 
> openTiming: true #是否开启定时功能 cron: "0 0 0 * * *" #自动签到时间 serverPort: 58613 #对外开放api端口号
> 
> commands.yml修改
> 
> genshin.mys.sign: type: order auth: 1 scope: 3 headers: - mysqd - mys签到 - 米游社签到 enable: true
> 
> ### **错误报告**
> 无错误报告

**Comment by wickedll** [comment]
重新登录获取一下cookie就可以了

**Comment by deYangar** [comment]
> 重新登录获取一下cookie就可以了

确实，之前的cookie太老了。不过一直能查询米游社啥的也就没留意，没想到签到不行。

还有就是，大佬有没有考虑把这个签到加进Adachi-BOT私人服务里面

**Comment by wickedll** [comment]
嗯  后面看看

**Comment by wickedll** [comment]
> > 重新登录获取一下cookie就可以了
> 
> 确实，之前的cookie太老了。不过一直能查询米游社啥的也就没留意，没想到签到不行。
> 
> 还有就是，大佬有没有考虑把这个签到加进Adachi-BOT私人服务里面

私人服务已更新

**Comment by tian564159391** [comment]
是重新登录

> 重新登录获取一下cookie就可以了

重新登录游戏还是米游社网页？重新登录米游社网页后按F12在控制台获取cookie 重新在私人服务添加cookie后还是不行 提示尚未登录 囧

**Comment by wickedll** [comment]
> 是重新登录
> 
> > 重新登录获取一下cookie就可以了
> 
> 重新登录游戏还是米游社网页？重新登录米游社网页后按F12在控制台获取cookie 重新在私人服务添加cookie后还是不行 提示尚未登录 囧

https://github.com/SilveryStar/Adachi-BOT/issues/134 可以参考这个
