### ISSUE TITLE
一定情况下不间断请求签到

### ISSUE THREAD

**Issue by MomentQYC** [wickedll/genshin_sign#2]
在没有执行npm stop而直接重启后，会一直请求签到，即使已经签到过且被机器人查询过
相关配置文件如下
openTiming: true #是否开启定时功能
cron: "0 0/2 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * *" #自动签到时间
serverPort: ***

**Comment by MomentQYC** [comment]
补充说明
系统Ubuntu20.04
NodeJS 16.15.1
主程序2.4.2fix
具体会先发SyntaxError: Unexpected token u in JSON at position 0
然后有签到信息

**Comment by MomentQYC** [comment]
新加一条，如果openTiming为false，访问页面会出现
Cannot GET /

**Comment by wickedll** [comment]
检测下cron表达式

**Comment by wickedll** [comment]
> 检测下cron表达式

检查

**Comment by MomentQYC** [comment]
> 检测下cron表达式

表达式在线查过，且在重启前一直正常

**Comment by wickedll** [comment]
> > 检测下cron表达式
> 
> 表达式在线查过，且在重启前一直正常

我咋看不懂这个表达式

**Comment by MomentQYC** [comment]
> > > 检测下cron表达式
> > 
> > 
> > 表达式在线查过，且在重启前一直正常
> 
> 我咋看不懂这个表达式

3-23点每两分钟一次，甚至还在生成的那种地方专门又生成了一遍又试运行了一遍

**Comment by MomentQYC** [comment]
我好像知道了点，是不是本插件一次性全部签到完毕而不是一个一个签

**Comment by wickedll** [comment]
> > > > 检测下cron表达式
> > > 
> > > 
> > > 表达式在线查过，且在重启前一直正常
> > 
> > 
> > 我咋看不懂这个表达式
> 
> 3-23点每两分钟一次，甚至还在生成的那种地方专门又生成了一遍又试运行了一遍

0 0/2 3-23 * * ? * 可以简化成这样

**Comment by wickedll** [comment]
> 我好像知道了点，是不是本插件一次性全部签到完毕而不是一个一个签

你说的没错

**Comment by MomentQYC** [comment]
> > 我好像知道了点，是不是本插件一次性全部签到完毕而不是一个一个签
> 
> 你说的没错

主要是一次性签大概率出现只能成功一个的情况

**Comment by wickedll** [comment]
> > > 我好像知道了点，是不是本插件一次性全部签到完毕而不是一个一个签
> > 
> > 
> > 你说的没错
> 
> 主要是一次性签大概率出现只能成功一个的情况

提示是什么 一次性签到也是一个一个轮流下来的  每个都会单独去请求  最近是有一个频率过快的问题

**Comment by MomentQYC** [comment]
> > > > 我好像知道了点，是不是本插件一次性全部签到完毕而不是一个一个签
> > > 
> > > 
> > > 你说的没错
> > 
> > 
> > 主要是一次性签大概率出现只能成功一个的情况
> 
> 提示是什么 一次性签到也是一个一个轮流下来的 每个都会单独去请求 最近是有一个频率过快的问题

只会有一个成功的给出提示
然后会有`SyntaxError: Unexpected token u in JSON at position 0`
根据反馈会发现没有成功提示并没有成功

**Comment by MomentQYC** [comment]
> > > > 我好像知道了点，是不是本插件一次性全部签到完毕而不是一个一个签
> > > 
> > > 
> > > 你说的没错
> > 
> > 
> > 主要是一次性签大概率出现只能成功一个的情况
> 
> 提示是什么 一次性签到也是一个一个轮流下来的 每个都会单独去请求 最近是有一个频率过快的问题

只会有一个成功的给出提示
然后会有`SyntaxError: Unexpected token u in JSON at position 0`
根据反馈会发现没有成功提示并没有成功

**Comment by wickedll** [comment]
> > > > > 我好像知道了点，是不是本插件一次性全部签到完毕而不是一个一个签
> > > > 
> > > > 
> > > > 你说的没错
> > > 
> > > 
> > > 主要是一次性签大概率出现只能成功一个的情况
> > 
> > 
> > 提示是什么 一次性签到也是一个一个轮流下来的 每个都会单独去请求 最近是有一个频率过快的问题
> 
> 只会有一个成功的给出提示 然后会有`SyntaxError: Unexpected token u in JSON at position 0` 根据反馈会发现没有成功提示并没有成功

你有几个cookie 出现这个提示后  后面的签到就停止了吗？ 一般这个提示为cookie问题

**Comment by wickedll** [comment]
然后现在私人服务里面有内嵌签到，你可以用那个
