### ISSUE TITLE
自动插件签到插件,  node版本V.16.14 , 插件未运行

### ISSUE THREAD

**Issue by Passerby-Fu** [wickedll/genshin_sign#7]
大佬 , 您好!!

本地拉取代码插件之后将其放入plugs中并参照文档进行部分修改 , 发现正常运行 , 但是未能启动服务 , 在启动方法中打印后发现未能运行 .
安装的插件 :
 1. mihoyo-login
 2. genshin_sign
 3. genshin
 
其中 genshin_sign 的init 修改为 
`export default definePlugin( {
	name: "genshin_sign",
	cfgList: [ sign, privateSign, ],
	repo: {
		owner: "wickedll",
		repoName: "genshin_sign", // 仓库名称
		ref: "main" // 分支名称
	},
	mounted() {

       // 再此进行打印发现并不会进入

		// 插件行为
		if(!signConfig.openTiming){
			createServer(signConfig, bot.logger);
		}
	}
} );`

运行日志截图
![image](https://github.com/user-attachments/assets/9315e1bf-96ee-4d86-81ff-56fb083cf85d)

正常运行后应该打印此下
![image](https://github.com/user-attachments/assets/0a8a74ee-f9bf-407c-9d58-d45d911eae25)

**Comment by wickedll** [comment]
好像原项目已内嵌签到服务 故此插件已不再使用

**Comment by Passerby-Fu** [comment]
已解决 , 打开定时签到可以运行 , 因为之前的项目进行了一些更新 , API改变所以导致未能运行签到服务 ; 但是为什么原项目内嵌的一些插件 , 在挂载的生命周期 ( mounted ) 内打印也未能运行呢 , 这一点我不是很明白

**Comment by wickedll** [comment]
具体 您可以到[https://github.com/SilveryStar/Adachi-BOT](url)这边问一下 因为我也好久没有查看原项目了
